apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-1
  labels:
    name: data-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: ""
  local:
    path: /some/path/in/container
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
