apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-2-pv
  namespace: flwr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: data-2
  storageClassName: ""
