apiVersion: v1
kind: Service
metadata:
  name: supernode-0
  namespace: flwr
  labels:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: "0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: "0"
  ports:
    - name: clientappio
      port: 9094
      targetPort: 9094
