apiVersion: v1
kind: Service
metadata:
  name: supernode-1
  namespace: flwr
  labels:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: "1"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supernode
    app.kubernetes.io/instance: "1"
  ports:
    - name: clientappio
      port: 9095
      targetPort: 9095
