version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"

tasks:
  clean-logs:
    desc: "🧹 Delete all lightning_logs folders"
    cmds:
      - cmd: gum style "🧹 Removing all Lightning logs..."
        silent: true
      - cmd: gum spin --spinner line --title "Deleting lightning_logs..." -- sleep 1
        silent: true
      - rm -rf lightning_logs
      - cmd: gum style "✅ Done! All Lightning logs have been cleaned."
        silent: true
